### PR TITLE
Add NEGINSTART and POSINTEND to tuple

### PR DESCRIPTION
**Pull request by garrensmith**
Adds support for NEGINSTART and POSINTEND so that the tuple binding tests pass.

I'm still pretty new to Rust so the code might not be the perfect rust way of doing it. But it does make the binding layer tests for tuples pass which is cool 🎉

### CODE REVIEW

**Comment by Speedy37** [comment]
Some related information about this, to help me review.

From https://github.com/apple/foundationdb/blob/master/design/tuple.md 

## Negative arbitrary-precision Integer

Typecodes: 0x0a, 0x0b Encoding: Not defined yet
Status: Reserved; 0x0b used in Python and Java

These typecodes are reserved for encoding integers larger than 8 bytes. Presumably the type code would be followed by some encoding of the length, followed by the big endian one’s complement number. Reserving two typecodes for each of positive and negative numbers is probably overkill, but until there’s a design in place we might as well not use them. In the Python and Java implementations, 0x0b stores negative numbers which are expressed with between 9 and 255 bytes. The first byte following the type code (0x0b) is a single byte expressing the number of bytes in the integer (with its bits flipped to preserve order), followed by that number of bytes representing the number in big endian order in one's complement.

## Positive arbitrary-precision Integer

Typecodes: 0x1d, 0x1e Encoding: Not defined yet
Status: Reserved; 0x1d used in Python and Java

These typecodes are reserved for encoding integers larger than 8 bytes. Presumably the type code would be followed by some encoding of the length, followed by the big endian one’s complement number. Reserving two typecodes for each of positive and negative numbers is probably overkill, but until there’s a design in place we might as well not use them. In the Python and Java implementations, 0x1d stores positive numbers which are expressed with between 9 and 255 bytes. The first byte following the type code (0x1d) is a single byte expressing the number of bytes in the integer, followed by that number of bytes representing the number in big endian order.

**Comment by Speedy37** [comment]
Nice one, I didn't notice the tuple test only required this.
Do you have any idea why Github actions aren't running?

Also we can now add i128 and u128 support to the tuple layer.
And maybe "num-bigint" as an optional dependency.
Those changes aren't necessary to merge this.

**Review by Speedy37 — CHANGES_REQUESTED** [review]

**Comment by garrensmith** [comment]
Awesome. Thanks for reviewing so quickly. I'll make the changes tomorrow. No idea why the actions are not triggering. Is there anything I can do to trigger that?

**Comment by Speedy37** [comment]
I guess they are not triggered because I only wrote `on: [push]` in `.github/workflows/ci.yml`.
I removed the `on: [push, pull_request]` to not double trigger the checks twice but it seems in this case it might be the cause.

**Comment by garrensmith** [comment]
@Speedy37 thanks for the review. I've made all the required fixes.

**Comment by garrensmith** [comment]
@Speedy37 could we for the checks to rerun again? I'm not sure why they are all failing

**Comment by Speedy37** [comment]
The initial run failed due to #170 and when I pressed re-run checks it failed at checkout...
I've made a few more changes on my side that I will push soon (more tests, code reuse and i128, u128 support).

**Comment by Speedy37** [comment]
Also I'm a bit confused by the current state of NEGINSTART and POSINTEND in the official repository:

This is wrong:
```cpp
if(data[i] >= NEG_INT_START && data[i] <= POS_INT_END) {
    i += abs(data[i] - INT_ZERO_CODE) + 1;
}
```
https://github.com/apple/foundationdb/blob/4f6054a3e6ff9321de3ff26b39b6151ada83e725/bindings/flow/Tuple.cpp#L108 

And in the java tuple layer tests, this seems wrong:

```
Tuple.from(BigInteger.valueOf(Long.MIN_VALUE).subtract(BigInteger.ONE)), new byte[]{0x0C, 0x7f, FF, FF, FF, FF, FF, FF, FF - 1},
```
https://github.com/apple/foundationdb/blob/b52eb746fdce92e4e0b44b96c54716836c44d518/bindings/java/src/test/com/apple/foundationdb/test/TupleTest.java#L121

**Comment by Speedy37** [comment]
Nevermind, it does pass the test, it's because we only requires bigint encoding when below -2^64.

**Review by Speedy37 — APPROVED** [review]

**Comment by garrensmith** [comment]
@Speedy37 some really nice improvements. Thanks for those

**Pull request merged**
