### PR TITLE
Clean up the `tuple` module

### PR DESCRIPTION
**Pull request by rushmorem**
As proposed in https://github.com/bluejekyll/foundationdb-rs/issues/68.

### CODE REVIEW

**Comment by rushmorem** [comment]
Yeah, I like that. I have updated the PR.

**Comment by rushmorem** [comment]
I've also implemented `Encode` for `&str` in this PR because that was going to require yet another breaking change.

**Comment by bluejekyll** [comment]
Awesome! Thanks!

**Comment by rushmorem** [comment]
Ah, you are absolutely right! I didn't think this through. I didn't need to put it in the variant. I will fix this shortly.

**Pull request merged**
