### PR TITLE
tuple: fix panic on i64

### PR DESCRIPTION
**Pull request by yjh0502**
related: https://github.com/bluejekyll/foundationdb-rs/issues/119

### CODE REVIEW

**Comment by yjh0502** [comment]
This PR is WIP. I'm working to find more edge cases on integer encoding/decoding.

**Comment by yjh0502** [comment]
@bluejekyll I fixed crash on encoding/decoding edge cases:

- encoding/decoding edge cases should work: `i64::min_value()`, `i64::min_value()+1`, `i64::max_value()`, `i64::max_value()-1`.
 - decoding non-representable values should return error: `i64::max_value()+1` and larger values, `i64::min_value()-1` and smaller values.

`i64::min_value()` is handled as a special case (Go also does it[0]), because it is an only value which `abs()` overflows.

[0] https://github.com/apple/foundationdb/blob/master/bindings/go/src/fdb/tuple/tuple.go#L557-L560

**Comment by bluejekyll** [comment]
Ok. Let me know when you’re ready for merge.

**Comment by yjh0502** [comment]
@bluejekyll The PR is ready for merge, thanks.

**Pull request merged**
