### PR TITLE
Class scheduling tutorial

### PR DESCRIPTION
**Pull request by bluejekyll**
Fixes: #31 

I need to go through and validate this still. It was derived from the Java tutorial, so it definitely can be more Rusty.

### CODE REVIEW

**Comment by bluejekyll** [comment]
Ok, before pushing this, I want to cleanup some of the interfaces... not too much though, as I want it to basically mimic the Tutorial from FoundationDB.

**Comment by bluejekyll** [comment]
A few more changes. I need to cleanup the `FdbError` for use in the `Database::transact`, almost finished that refactor, but am out of time tonight.

Once that's done, I can convert to using `transact` as required in the tutorial.

**Comment by bluejekyll** [comment]
After #77 lands, I think this is ready. And then I say we publish the next release.

**Comment by bluejekyll** [comment]
This depends on #77

**Comment by bluejekyll** [comment]
Ok, I might go back and interleave the tutorial with the code later.

**Comment by rushmorem** [comment]
OK

**Pull request merged**
